function [TD, EM] = ReadAER(filename)
% [TD, EM] = ReadAER(filename) 
% Reads in data from a ".val" file generated by the ATIS GUI v4.2 onwards
%
% TD contains the "Temporal Difference" events (DVS events)
% 
% EM contains the grayscale "Exposure Measurement" events (EM events)
% 
% If reading in datasets (N-Caltech101 or N-MNIST) use the functions
% included with the dataset instead.

videoData = fopen(filename);
temp = fread(videoData);
fclose(videoData);

TD.y = 1+ temp(4:4:end);
TD.x = 1+ bitshift(bitand(temp(2:4:end),32),3)  + temp(3:4:end); %bit 5
TD.p = bitshift(bitand(temp(2:4:end), 128), -7); %bit 7
Type = bitshift(bitand(temp(2:4:end), 64), -6); %bit 6
TD.ts = temp(1:4:end) + bitshift((bitand(temp(2:4:end), 31)), 8);% bit 4 downto 0

timeOffset = 0;
for i = 1:length(TD.ts)
    if ((TD.y(i) == 241) && (TD.x(i) ==306))
        TD.ts(i) = 0;
        timeOffset = timeOffset + 2^13;
    else
        TD.ts(i) = TD.ts(i) + timeOffset;
    end
end

%
TD = RemoveNulls(TD, TD.ts==0);
Type = Type(TD.ts~=0);

EM = RemoveNulls(TD, Type == 0);
TD = RemoveNulls(TD, Type == 1);